version: "3.8"
services:
  database:
    container_name: garretts_watch_todos
    image: postgres:15-alpine
    # Load all env vars from .env into the container's environment.
    env_file: .env
    ports:
      - 5433:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      # - ./api/src/db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      # - ./api/src/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  pgadmin:
    container_name: tasks_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: phillip.witkin@galvanize.com
      PGADMIN_DEFAULT_PASSWORD: docker
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  pg-data:
  pgadmin-data:
